### PR TITLE
Tags UI

### PR DESCRIPTION
**Pull request by WesleyRomanTaylor**

### CODE REVIEW

**Review by kyleerin — CHANGES_REQUESTED** [review]
Looks like you brought in some changes from main. Before you merge this, we should pull latest changes from main to ui.

**Comment by WesleyRomanTaylor** [comment]
@brocwoodworthIBLX Yes i was trying to merge into ui. I will work with kyle to get this into main
@kyleerin I believe i have fixed the issue.

**Review by brocwoodworthIBLX — CHANGES_REQUESTED** [review]
this isn't quite right. `grpc.go` and `tools.go` are from older commits. you might need to merge again?

**Comment by WesleyRomanTaylor** [comment]
this quickly turned to garbage i am merging into main.

**Pull request closed without merging**
